# 15 NOV

### use of import keyword

In [1]:
x=sqrt(25)
x

NameError: name 'sqrt' is not defined

In [5]:
help()

Welcome to Python 3.12's help utility! If this is your first time using
Python, you should definitely check out the tutorial at
https://docs.python.org/3.12/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To get a list of available
modules, keywords, symbols, or topics, enter "modules", "keywords",
"symbols", or "topics".

Each module also comes with a one-line summary of what it does; to list
the modules whose name or summary contain a given string such as "spam",
enter "modules spam".

To quit this help utility and return to the interpreter,
enter "q" or "quit".



help>  math


Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.

        The result is between 0 and pi.

    acosh(x, /)
        Return the inverse hyperbolic cosine of x.

    asin(x, /)
        Return the arc sine (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    asinh(x, /)
        Return the inverse hyperbolic sine of x.

    atan(x, /)
        Return the arc tangent (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.

        Unlike atan(y/x), the signs of both x and y are considered.

    atanh(x, /)
        Return the inverse hyperbolic tangent of x.

    cbrt(x, /)
        Return the cube root of x.

    ceil(x, /)
        Return the ceiling of x as an Integral.

        This i

help>  q



You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.


In [7]:
import math

In [9]:
x=math.sqrt(25)
x

5.0

In [13]:
x1=math.sqrt(15)
x1

3.872983346207417

In [15]:
math.floor(3.67)
#range is between 3 to 4
# floor meand least or minimum value

3

In [17]:
math.ceil(3.67)
# ceil means highest or maximum value

4

In [19]:
math.pow(3,2)

9.0

In [21]:
math.pi

3.141592653589793

In [23]:
math.e

2.718281828459045

In [25]:
m.sqrt(25)

NameError: name 'm' is not defined

In [27]:
import math as m

In [29]:
m.sqrt(25)

5.0

In [31]:
m.pow(8,9)

134217728.0

In [33]:
m.pow(8,3)

512.0

In [39]:
m.floor(4.3)

4

In [37]:
m.ceil(4.3)

5

In [41]:
m.pi

3.141592653589793

In [43]:
m.e

2.718281828459045

In [51]:
from math import sqrt,pow
print(pow(2,3))
print(m.sqrt(36))

8.0
6.0


In [61]:
from math import sqrt,pow,
print(pow(2,3))
print(sqrt(36))
print(floor(2.3))
print(ceil(2.3))

SyntaxError: trailing comma not allowed without surrounding parentheses (2963930447.py, line 1)

In [57]:
from math import sqrt,pow,floor,ceil
print(pow(2,3))
print(m.sqrt(36))
print(floor(2.3))
print(ceil(2.3))

8.0
6.0
2
3


In [63]:
print(pi)

NameError: name 'pi' is not defined

In [67]:
from math import * 
# * means all the function of math
print(pow(2,3))
print(sqrt(12))
print(floor(9.8))
print(ceil(9.8))

8.0
3.4641016151377544
9
10


# INPUT() FUNCTION

In [70]:
x=input()
x

 hello


'hello'

In [72]:
type(x)

str

In [82]:
x=input()
y=input()
z=x+y
print(z)

 3
 4


34


In [80]:
type(z)

str

In [84]:
x1=input('enter the 1st number')
y1=input('enter the 2nd number')
z1=x1+y1
print(z1)

enter the 1st number 10
enter the 2nd number 5


105


In [86]:
print(type(x1))
print(type(y1))

<class 'str'>
<class 'str'>


In [88]:
x1=input('enter the 1st number')
a1=int(x1)
yi=input('enter the 2nd number')
b1=int(y1)
z1=a1+b1
print(z1)

enter the 1st number 10
enter the 2nd number 5


15


In [92]:
x2=int(input('enter the 1st number'))
y2=int(input('enter the 2nd number'))
z2=x2+y2
z2

enter the 1st number 10
enter the 2nd number 5


15

In [94]:
ch=input('enter the char')
ch

enter the char pavani


'pavani'

In [96]:
ch=input('enter the char')
ch

enter the char 99


'99'

In [98]:
print(ch[0])

9


In [100]:
ch=input('enter the char')
ch

enter the char hello


'hello'

In [102]:
ch[0]

'h'

In [104]:
ch=input('enter the char')[0]
ch

enter the char hello


'h'

In [106]:
ch=input('enter the char')[1:3]
ch

enter the char hello


'el'

In [110]:
ch=input('enter the char')[::-1]
ch

enter the char hello


'olleh'

In [112]:
st=input('enter the st')[::-1]
st

enter the st hello


'olleh'

In [114]:
st=input('enter the string')
st

enter the string hello


'hello'

In [116]:
st[0]

'h'

In [118]:
st=input('enter the string')[0]
st

enter the string hello


'h'

In [122]:
result=input('enter an expr')
result

enter an expr 89+35


'89+35'

In [124]:
result=eval(input('enter an expr'))
result
print(result)

enter an expr 89+35


124


# 16 NOV

## NUMPY

In [5]:
import numpy as np

In [7]:
np.__version__

'1.26.4'

### create array

In [10]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [12]:
type(my_list)

list

In [14]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [16]:
type(arr)

numpy.ndarray

In [18]:
type(my_list)

list

In [24]:
np. # we learn important functions

SyntaxError: invalid syntax (502722002.py, line 1)

In [26]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
np.arange(3.0)

array([0., 1., 2.])

In [32]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [38]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [54]:
np.arange(20,10)
#1st argument always be < 2nd argument

array([], dtype=int32)

In [56]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [58]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [60]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [62]:
np.arange(30,20)

array([], dtype=int32)

In [64]:
ar=np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [66]:
np.arange(10,10)

array([], dtype=int32)

In [68]:
np.arange()

TypeError: arange() requires stop to be specified.

In [70]:
np.arange(10,30,5)
# starting from 10 with count of 5 to 30

array([10, 15, 20, 25])

In [72]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [74]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [76]:
np.zeros(3)

array([0., 0., 0.])

In [78]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [80]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [86]:
zero=np.zeros([2,2])
print(zero)
print('####')
print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [88]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [90]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [92]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [94]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [98]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [100]:
n=(6,7)
n1=(6,8)
print(np.zeros(n))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [102]:
n=(6,7)
n1=(6,8)
print(np.zeros(6,7))

TypeError: Cannot interpret '7' as a data type

In [104]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [106]:
np.ones(3)

array([1., 1., 1.])

In [108]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [114]:
n
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [116]:
n1
np.ones(n1)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [118]:
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [120]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [122]:
np.three((2,3))

AttributeError: module 'numpy' has no attribute 'three'